cp -r pre_snapshot pre_snapshot-qemu_xhci-0
cp -r pre_snapshot pre_snapshot-legacy_ac97-0
cp -r pre_snapshot pre_snapshot-legacy_cs4231a-0
cp -r pre_snapshot pre_snapshot-legacy_es1370-0
cp -r pre_snapshot pre_snapshot-legacy_intel_hda-0
cp -r pre_snapshot pre_snapshot-legacy_sb16-0
cp -r pre_snapshot pre_snapshot-legacy_parallel-0
cp -r pre_snapshot pre_snapshot-legacy_serial-0
cp -r pre_snapshot pre_snapshot-legacy_floppy-0
cp -r pre_snapshot pre_snapshot-legacy_ide_core-0
cp -r pre_snapshot pre_snapshot-legacy_sdhci-0
cp -r pre_snapshot pre_snapshot-legacy_ee100pro-0
cp -r pre_snapshot pre_snapshot-legacy_e1000-0
cp -r pre_snapshot pre_snapshot-legacy_ne2000-0
cp -r pre_snapshot pre_snapshot-legacy_pcnet-0
cp -r pre_snapshot pre_snapshot-legacy_rtl8139-0
cp -r pre_snapshot pre_snapshot-legacy_xhci-0
