bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-legacy_ac97-
bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-legacy_cs4231a-
bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-legacy_e1000-
bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-legacy_ee100pro-
bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-legacy_es1370-
bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-legacy_floppy-
bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-legacy_intelhda-
bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-legacy_ne2000-
bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-legacy_pcnet-
bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-legacy_rtl8139-
bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-legacy_sb16-
bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-legacy_sdhci-
bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-legacy_xhci-
bash ./11-cov.sh /media/hdd0/qiliu/workdir_qemu-qemu_xhci-
