mv nyx-qemu-legacy_ac97-none-profiles.merged ../evaluation/nyx-qemu-legacy_ac97-none-profiles
mv nyx-qemu-legacy_cs4231a-none-profiles.merged ../evaluation/nyx-qemu-legacy_cs4231a-none-profiles
mv nyx-qemu-legacy_e1000-none-profiles.merged ../evaluation/nyx-qemu-legacy_e1000-none-profiles
mv nyx-qemu-legacy_ee100pro-none-profiles.merged ../evaluation/nyx-qemu-legacy_ee100pro-none-profiles
mv nyx-qemu-legacy_es1370-none-profiles.merged ../evaluation/nyx-qemu-legacy_es1370-none-profiles
mv nyx-qemu-legacy_floppy-none-profiles.merged ../evaluation/nyx-qemu-legacy_floppy-none-profiles
mv nyx-qemu-legacy_intelhda-none-profiles.merged ../evaluation/nyx-qemu-legacy_ne2000-none-profiles
mv nyx-qemu-legacy_ne2000-none-profiles.merged ../evaluation/nyx-qemu-legacy_intelhda-none-profiles
mv nyx-qemu-legacy_pcnet-none-profiles.merged ../evaluation/nyx-qemu-legacy_pcnet-none-profiles
mv nyx-qemu-legacy_rtl8139-none-profiles.merged ../evaluation/nyx-qemu-legacy_rtl8139-none-profiles
mv nyx-qemu-legacy_sb16-none-profiles.merged ../evaluation/nyx-qemu-legacy_sb16-none-profiles
mv nyx-qemu-legacy_sdhci-none-profiles.merged ../evaluation/nyx-qemu-legacy_sdhci-none-profiles
mv nyx-qemu-legacy_xhci-none-profiles.merged ../evaluation/nyx-qemu-legacy_xhci-none-profiles
mv nyx-qemu-qemu_xhci-none-profiles.merged ../evaluation/nyx-qemu-qemu_xhci-none-profiles
