#!/bin/bash -x
./build_sharedir_standalone.sh qemu_xhci
./build_sharedir_standalone.sh legacy_ac97
./build_sharedir_standalone.sh legacy_cs4231a
./build_sharedir_standalone.sh legacy_es1370
./build_sharedir_standalone.sh legacy_intelhda
./build_sharedir_standalone.sh legacy_sb16
./build_sharedir_standalone.sh legacy_parallel
./build_sharedir_standalone.sh legacy_serial
./build_sharedir_standalone.sh legacy_floppy
./build_sharedir_standalone.sh legacy_ide_core
./build_sharedir_standalone.sh legacy_sdhci
./build_sharedir_standalone.sh legacy_ee100pro
./build_sharedir_standalone.sh legacy_e1000
./build_sharedir_standalone.sh legacy_ne2000
./build_sharedir_standalone.sh legacy_pcnet
./build_sharedir_standalone.sh legacy_rtl8139
./build_sharedir_standalone.sh legacy_xhci
